import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Toaster } from 'react-hot-toast'

import './globals.css'

import QueryProvider from '@/lib/providers/QueryProvider'
import SessionProvider from '@/lib/providers/SessionProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<SessionProvider>
			<QueryProvider>
				<html lang="en">
					<body className={`${inter.className} `}>
						<Toaster />
						<div className="max-w-[1920px] mx-auto h-[100vh]">
							{children}
						</div>
					</body>
				</html>
			</QueryProvider>
		</SessionProvider>
	)
}
