import dynamic from 'next/dynamic'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Toaster } from 'react-hot-toast'

import './globals.css'

import QueryProvider from '@/lib/providers/QueryProvider'
import SessionProvider from '@/lib/providers/SessionProvider'

import { getServerSession } from 'next-auth'
import { authOptions } from './api/auth/[...nextauth]/route'

const inter = Inter({ subsets: ['latin'] })

const FriendsBar = dynamic(() => import('@/components/friendsbar/FriendsBar'))
const LeftSidebar = dynamic(() => import('@/components/leftsidebar/LeftSidebar'))
const Navbar = dynamic(() => import('@/components/navbar/Navbar'))
const RightTabs = dynamic(() => import('@/components/righttabs/RightTabs'))

export const metadata: Metadata = {
	title: 'Huddle',
	description: 'Generated by create next app'
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
	const session = await getServerSession(authOptions)

	return (
		<SessionProvider>
			<QueryProvider>
				<html lang="en">
					<body className={`${inter.className} ${session ? 'bg-lg' : ''}`}>
						<Toaster />
						<div className="max-w-[1920px] mx-auto h-[100vh] flex flex-col">
							{session ? <Navbar /> : null}
							{!session ? children : <div className="flex flex-1">
								<LeftSidebar />
								{children}
								<RightTabs />
								<FriendsBar />
								<div className="h-[400vh]"></div>
							</div>}
						</div>
					</body>
				</html>
			</QueryProvider>
		</SessionProvider>
	)
}
